// @axioledger/interchain-security — Shared Validator Security
// Namespace: github.com/axioledger/interchain-security
// Source:    external/cosmos/interchain-security/
// Proto:     10 files · 100 messages · 2 services
// SDK:       packages/axioledger/sdk/src/generated/
"use strict";
module.exports = {
  _package:    "@axioledger/interchain-security",
  _version:    "2.0.22",
  _namespace:  "github.com/axioledger/interchain-security",
  _source:     "external/cosmos/interchain-security",
  _protoPkgs:  ["interchain_security.ccv.consumer.v1","interchain_security.ccv.provider.v1","interchain_security.ccv.v1"],
  _protoCount: 10,
  _messages:   ["CrossChainValidator","SlashRecord","GenesisState","HeightToValsetUpdateID","OutstandingDowntime","LastTransmissionBlockHeight","ConsumerPacketDataList","NextFeeDistributionEstimate","QueryNextFeeDistributionEstimateRequest","QueryNextFeeDistributionEstimateResponse","QueryParamsRequest","QueryParamsResponse","QueryProviderInfoRequest","QueryProviderInfoResponse","QueryThrottleStateRequest","QueryThrottleStateResponse","ChainInfo","MsgUpdateParams","MsgUpdateParamsResponse","ConsumerState","ValsetUpdateIdToHeight","ConsumerAdditionProposal","ConsumerRemovalProposal","ConsumerModificationProposal","EquivocationProposal","ChangeRewardDenomsProposal","GlobalSlashEntry","Params","SlashAcks","ConsumerAdditionProposals","ConsumerRemovalProposals","AddressList","ChannelToChain","ValidatorSetChangePackets","KeyAssignmentReplacement","ValidatorConsumerPubKey","ValidatorByConsumerAddr","ConsumerAddrsToPruneV2","ConsensusValidator","ConsumerRewardsAllocation","ConsumerMetadata","ConsumerInitializationParameters","PowerShapingParameters","ConsumerIds","AllowlistedRewardDenoms","InfractionParameters","SlashJailParameters","QueryConsumerGenesisRequest","QueryConsumerGenesisResponse","QueryConsumerChainsRequest","QueryConsumerChainsResponse","Chain","QueryValidatorConsumerAddrRequest","QueryValidatorConsumerAddrResponse","QueryValidatorProviderAddrRequest","QueryValidatorProviderAddrResponse","QueryRegisteredConsumerRewardDenomsRequest","QueryRegisteredConsumerRewardDenomsResponse","QueryAllPairsValConsAddrByConsumerRequest","QueryAllPairsValConsAddrByConsumerResponse","PairValConAddrProviderAndConsumer","QueryConsumerChainOptedInValidatorsRequest","QueryConsumerChainOptedInValidatorsResponse","QueryConsumerValidatorsRequest","QueryConsumerValidatorsValidator","QueryConsumerValidatorsResponse","QueryConsumerChainsValidatorHasToValidateRequest","QueryConsumerChainsValidatorHasToValidateResponse","QueryValidatorConsumerCommissionRateRequest","QueryValidatorConsumerCommissionRateResponse","QueryBlocksUntilNextEpochRequest","QueryBlocksUntilNextEpochResponse","QueryConsumerIdFromClientIdRequest","QueryConsumerIdFromClientIdResponse","QueryConsumerChainRequest","QueryConsumerChainResponse","QueryConsumerGenesisTimeRequest","QueryConsumerGenesisTimeResponse","MsgAssignConsumerKey","MsgAssignConsumerKeyResponse","MsgSubmitConsumerMisbehaviour","MsgSubmitConsumerMisbehaviourResponse","MsgSubmitConsumerDoubleVoting","MsgSubmitConsumerDoubleVotingResponse","MsgConsumerAddition","MsgConsumerRemoval","MsgRemoveConsumer","MsgRemoveConsumerResponse","MsgChangeRewardDenoms","MsgChangeRewardDenomsResponse","MsgOptIn","MsgOptInResponse","MsgOptOut","MsgOptOutResponse","MsgSetConsumerCommissionRate","MsgSetConsumerCommissionRateResponse","MsgConsumerModification","MsgConsumerModificationResponse","MsgCreateConsumer","MsgCreateConsumerResponse"],
  _services:   ["Query","Msg"],
  _enums:      ["ConsumerPhase","ConsumerPacketDataType","InfractionType"],
};
