// @axioledger/cosmos-sdk — Cosmos SDK — auth/bank/staking/gov/distribution
// Namespace: github.com/axioledger/cosmos-sdk
// Source:    external/cosmos/cosmos-sdk/
// Proto:     124 files · 100 messages · 6 services
// SDK:       packages/axioledger/sdk/src/generated/
"use strict";
module.exports = {
  _package:    "@axioledger/cosmos-sdk",
  _version:    "2.0.22",
  _namespace:  "github.com/axioledger/cosmos-sdk",
  _source:     "external/cosmos/cosmos-sdk",
  _protoPkgs:  ["amino","cosmos.app.runtime.v1alpha1","cosmos.app.v1alpha1","cosmos.auth.module.v1","cosmos.auth.v1beta1","cosmos.authz.module.v1","cosmos.authz.v1beta1","cosmos.autocli.v1","cosmos.bank.module.v1","cosmos.bank.v1beta1","cosmos.base.abci.v1beta1","cosmos.base.node.v1beta1","cosmos.base.query.v1beta1","cosmos.base.reflection.v1beta1","cosmos.base.reflection.v2alpha1","cosmos.base.tendermint.v1beta1","cosmos.base.v1beta1","cosmos.consensus.module.v1","cosmos.consensus.v1","cosmos.counter.module.v1","cosmos.counter.v1","cosmos.crypto.bls12_381","cosmos.crypto.ed25519","cosmos.crypto.hd.v1","cosmos.crypto.keyring.v1","cosmos.crypto.mldsa65","cosmos.crypto.multisig","cosmos.crypto.multisig.v1beta1","cosmos.crypto.secp256k1","cosmos.crypto.secp256k1eth","cosmos.crypto.secp256r1","cosmos.distribution.module.v1","cosmos.distribution.v1beta1","cosmos.epochs.module.v1","cosmos.epochs.v1beta1","cosmos.evidence.module.v1","cosmos.evidence.v1beta1","cosmos.feegrant.module.v1","cosmos.feegrant.v1beta1","cosmos.genutil.module.v1","cosmos.genutil.v1beta1","cosmos.gov.module.v1","cosmos.gov.v1","cosmos.gov.v1beta1","cosmos.mint.module.v1","cosmos.mint.v1beta1","cosmos.msg.v1","cosmos.query.v1","cosmos.reflection.v1","cosmos.slashing.module.v1","cosmos.slashing.v1beta1","cosmos.staking.module.v1","cosmos.staking.v1beta1","cosmos.store.internal.kv.v1beta1","cosmos.store.snapshots.v1","cosmos.store.streaming.abci","cosmos.store.v1beta1","cosmos.tx.config.v1","cosmos.tx.signing.v1beta1","cosmos.tx.v1beta1","cosmos.upgrade.module.v1","cosmos.upgrade.v1beta1","cosmos.vesting.module.v1","cosmos.vesting.v1beta1","tendermint.abci","tendermint.crypto","tendermint.libs.bits","tendermint.p2p","tendermint.types","tendermint.version"],
  _protoCount: 124,
  _messages:   ["Module","StoreKeyConfig","Config","ModuleConfig","GolangBinding","ModuleDescriptor","PackageReference","MigrateFromInfo","QueryConfigRequest","QueryConfigResponse","ModuleAccountPermission","BaseAccount","ModuleAccount","ModuleCredential","Params","GenesisState","QueryAccountsRequest","QueryAccountsResponse","QueryAccountRequest","QueryAccountResponse","QueryParamsRequest","QueryParamsResponse","QueryModuleAccountsRequest","QueryModuleAccountsResponse","QueryModuleAccountByNameRequest","QueryModuleAccountByNameResponse","Bech32PrefixRequest","Bech32PrefixResponse","AddressBytesToStringRequest","AddressBytesToStringResponse","AddressStringToBytesRequest","AddressStringToBytesResponse","QueryAccountAddressByIDRequest","QueryAccountAddressByIDResponse","QueryAccountInfoRequest","QueryAccountInfoResponse","MsgUpdateParams","MsgUpdateParamsResponse","GenericAuthorization","Grant","GrantAuthorization","GrantQueueItem","EventGrant","EventRevoke","QueryGrantsRequest","QueryGrantsResponse","QueryGranterGrantsRequest","QueryGranterGrantsResponse","QueryGranteeGrantsRequest","QueryGranteeGrantsResponse","MsgGrant","MsgGrantResponse","MsgExec","MsgExecResponse","MsgRevoke","MsgRevokeResponse","ModuleOptions","ServiceCommandDescriptor","RpcCommandOptions","FlagOptions","PositionalArgDescriptor","AppOptionsRequest","AppOptionsResponse","SendAuthorization","SendEnabled","Input","Output","Supply","DenomUnit","Metadata","Balance","QueryBalanceRequest","QueryBalanceResponse","QueryAllBalancesRequest","QueryAllBalancesResponse","QuerySpendableBalancesRequest","QuerySpendableBalancesResponse","QuerySpendableBalanceByDenomRequest","QuerySpendableBalanceByDenomResponse","QueryTotalSupplyRequest","QueryTotalSupplyResponse","QuerySupplyOfRequest","QuerySupplyOfResponse","QueryDenomsMetadataRequest","QueryDenomsMetadataResponse","QueryDenomMetadataRequest","QueryDenomMetadataResponse","QueryDenomMetadataByQueryStringRequest","QueryDenomMetadataByQueryStringResponse","QueryDenomOwnersRequest","DenomOwner","QueryDenomOwnersResponse","QueryDenomOwnersByQueryRequest","QueryDenomOwnersByQueryResponse","QuerySendEnabledRequest","QuerySendEnabledResponse","MsgSend","MsgSendResponse","MsgMultiSend","MsgMultiSendResponse"],
  _services:   ["Query","Msg","Service","ReflectionService","ABCIListenerService","ABCI"],
  _enums:      ["VoteOption","ProposalStatus","AuthorizationType","BondStatus","Infraction","SignMode","OrderBy","BroadcastMode","CheckTxType","Result","VerifyStatus","MisbehaviorType","SignedMsgType","BlockIDFlag"],
};
