// @axioledger/ibc-go — IBC Protocol v11 — channel/client/transfer
// Namespace: github.com/axioledger/ibc-go
// Source:    external/cosmos/ibc-go/
// Proto:     60 files · 100 messages · 2 services
// SDK:       packages/axioledger/sdk/src/generated/
"use strict";
module.exports = {
  _package:    "@axioledger/ibc-go",
  _version:    "2.0.22",
  _namespace:  "github.com/axioledger/ibc-go",
  _source:     "external/cosmos/ibc-go",
  _protoPkgs:  ["ibc.applications.gmp.v1","ibc.applications.interchain_accounts.controller.v1","ibc.applications.interchain_accounts.genesis.v1","ibc.applications.interchain_accounts.host.v1","ibc.applications.interchain_accounts.v1","ibc.applications.packet_forward_middleware.v1","ibc.applications.rate_limiting.v1","ibc.applications.transfer.v1","ibc.core.channel.v1","ibc.core.channel.v2","ibc.core.client.v1","ibc.core.client.v2","ibc.core.commitment.v1","ibc.core.commitment.v2","ibc.core.connection.v1","ibc.core.types.v1","ibc.lightclients.attestations.v1","ibc.lightclients.solomachine.v2","ibc.lightclients.solomachine.v3","ibc.lightclients.tendermint.v1","ibc.lightclients.wasm.v1"],
  _protoCount: 60,
  _messages:   ["AccountIdentifier","ICS27Account","CosmosTx","GenesisState","RegisteredICS27Account","GMPPacketData","Acknowledgement","QueryAccountAddressRequest","QueryAccountAddressResponse","QueryAccountIdentifierRequest","QueryAccountIdentifierResponse","MsgSendCall","MsgSendCallResponse","Params","QueryInterchainAccountRequest","QueryInterchainAccountResponse","QueryParamsRequest","QueryParamsResponse","MsgRegisterInterchainAccount","MsgRegisterInterchainAccountResponse","MsgSendTx","MsgSendTxResponse","MsgUpdateParams","MsgUpdateParamsResponse","ControllerGenesisState","HostGenesisState","ActiveChannel","RegisteredInterchainAccount","QueryRequest","MsgModuleQuerySafe","MsgModuleQuerySafeResponse","InterchainAccount","Metadata","InterchainAccountPacketData","InFlightPacket","QueryAllRateLimitsRequest","QueryAllRateLimitsResponse","QueryRateLimitRequest","QueryRateLimitResponse","QueryRateLimitsByChainIDRequest","QueryRateLimitsByChainIDResponse","QueryRateLimitsByChannelOrClientIDRequest","QueryRateLimitsByChannelOrClientIDResponse","QueryAllBlacklistedDenomsRequest","QueryAllBlacklistedDenomsResponse","QueryAllWhitelistedAddressesRequest","QueryAllWhitelistedAddressesResponse","Path","Quota","Flow","RateLimit","WhitelistedAddressPair","HourEpoch","MsgAddRateLimit","MsgAddRateLimitResponse","MsgUpdateRateLimit","MsgUpdateRateLimitResponse","MsgRemoveRateLimit","MsgRemoveRateLimitResponse","MsgResetRateLimit","MsgResetRateLimitResponse","Allocation","TransferAuthorization","DenomTrace","FungibleTokenPacketData","QueryDenomRequest","QueryDenomResponse","QueryDenomsRequest","QueryDenomsResponse","QueryDenomHashRequest","QueryDenomHashResponse","QueryEscrowAddressRequest","QueryEscrowAddressResponse","QueryTotalEscrowForDenomRequest","QueryTotalEscrowForDenomResponse","Token","Denom","Hop","MsgTransfer","MsgTransferResponse","Channel","IdentifiedChannel","Counterparty","Packet","PacketState","PacketId","Timeout","PacketSequence","QueryChannelRequest","QueryChannelResponse","QueryChannelsRequest","QueryChannelsResponse","QueryConnectionChannelsRequest","QueryConnectionChannelsResponse","QueryChannelClientStateRequest","QueryChannelClientStateResponse","QueryChannelConsensusStateRequest","QueryChannelConsensusStateResponse","QueryPacketCommitmentRequest","QueryPacketCommitmentResponse"],
  _services:   ["Query","Msg"],
  _enums:      ["Type","PacketDirection","State","Order","ResponseResultType","PacketStatus","DataType"],
};
