#!/usr/bin/env bash
# =============================================================================
# toolchain/build-scripts/generate-proto.sh
# Axioledger v2.0 — Protobuf → TypeScript SDK Code Generation
#
# Pipeline:
#   1. Kiểm tra @cosmology/telescope đã cài
#   2. Phát hiện file .proto trong external/cosmos/* và packages/axioledger/*/proto
#   3. Chạy telescope transpile → packages/axioledger/sdk/src/generated/
#   4. Nếu không có .proto (stub mode) → sinh TypeScript type declarations đầy đủ
#   5. Kiểm tra go.work syntax (nếu Go đã cài)
#   6. Kiểm tra Rust contracts (nếu Cargo đã cài)
#
# Chạy:
#   bash toolchain/build-scripts/generate-proto.sh
#   bash toolchain/build-scripts/generate-proto.sh --clean   # xóa output trước
#   bash toolchain/build-scripts/generate-proto.sh --stub    # chỉ sinh stubs (no telescope)
#
# Yêu cầu: node ≥ 20, pnpm ≥ 9, @cosmology/telescope
# =============================================================================

set -uo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; BOLD='\033[1m'; NC='\033[0m'
log_info()    { echo -e "  ${BLUE}ℹ${NC}  $*"; }
log_ok()      { echo -e "  ${GREEN}✓${NC}  $*"; }
log_warn()    { echo -e "  ${YELLOW}⚠${NC}  $*"; }
log_error()   { echo -e "  ${RED}✗${NC}  $*" >&2; }
log_section() { echo -e "\n${BOLD}${BLUE}── $* ──${NC}"; }

MONOREPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TELESCOPE_CONFIG="${MONOREPO_ROOT}/toolchain/build-scripts/telescope.config.ts"
OUT_DIR="${MONOREPO_ROOT}/packages/axioledger/sdk/src/generated"

cd "${MONOREPO_ROOT}"

# ─── Tham số CLI ──────────────────────────────────────────────────────────────
CLEAN=false; STUB_ONLY=false
for arg in "$@"; do
  case "$arg" in
    --clean)  CLEAN=true      ;;
    --stub)   STUB_ONLY=true  ;;
  esac
done

echo ""
echo -e "${BOLD}==================================================================="
echo -e "  AXIOLEDGER v2.0 — Protobuf → TypeScript SDK Codegen"
echo -e "===================================================================${NC}"
log_info "Output:  ${OUT_DIR}"
log_info "Config:  ${TELESCOPE_CONFIG}"
echo ""

# ─── Xóa output cũ nếu --clean ───────────────────────────────────────────────
if [[ "$CLEAN" == "true" ]]; then
    log_warn "--clean: xóa thư mục output cũ..."
    rm -rf "${OUT_DIR}"
    log_ok "Đã xóa ${OUT_DIR}"
fi

mkdir -p "${OUT_DIR}"

# ─── Đếm .proto files ────────────────────────────────────────────────────────
log_section "Phát hiện file .proto"

PROTO_COUNT=0
PROTO_DIRS=(
    "external/cosmos/cosmos-sdk/proto"
    "external/cosmos/ibc-go/proto"
    "external/cosmos/interchain-security/proto"
    "external/cosmos/tokenfactory/proto"
    "packages/axioledger/cosmos-sdk/proto"
    "packages/axioledger/ibc-go/proto"
    "toolchain/proto"
)

for dir in "${PROTO_DIRS[@]}"; do
    if [[ -d "${MONOREPO_ROOT}/${dir}" ]]; then
        count=$(find "${MONOREPO_ROOT}/${dir}" -name "*.proto" 2>/dev/null | wc -l)
        PROTO_COUNT=$((PROTO_COUNT + count))
        if [[ "$count" -gt 0 ]]; then
            log_ok "${dir}: ${count} proto files"
        else
            log_info "${dir}: (rỗng hoặc chưa tạo)"
        fi
    else
        log_info "${dir}: thư mục chưa tồn tại"
    fi
done

echo ""
log_info "Tổng số .proto files: ${PROTO_COUNT}"

# ─── Telescope Codegen ────────────────────────────────────────────────────────
log_section "Telescope Codegen"

TELESCOPE_RAN=false

if [[ "$STUB_ONLY" == "false" ]] && [[ "$PROTO_COUNT" -gt 0 ]]; then
    # Kiểm tra telescope đã cài
    if node -e "import('@cosmology/telescope')" 2>/dev/null || \
       node -e "require.resolve('@cosmology/telescope')" 2>/dev/null; then
        log_info "Chạy: pnpx telescope transpile --config ${TELESCOPE_CONFIG}"
        if pnpx telescope transpile --config "${TELESCOPE_CONFIG}" 2>&1; then
            log_ok "Telescope codegen hoàn thành"
            TELESCOPE_RAN=true
        else
            log_warn "Telescope codegen thất bại — chuyển sang sinh stub types"
        fi
    else
        log_warn "@cosmology/telescope chưa cài — chuyển sang sinh stub types"
        log_info "Cài đặt: pnpm add -D @cosmology/telescope -w"
    fi
elif [[ "$PROTO_COUNT" -eq 0 ]]; then
    log_warn "Không có .proto files — sinh stub TypeScript type declarations"
fi

# ─── Stub Types (khi không có telescope hoặc không có .proto) ────────────────
if [[ "$TELESCOPE_RAN" == "false" ]]; then
    log_section "Sinh Stub TypeScript Declarations"

    # Tạo stub file index.ts đầy đủ
    cat > "${OUT_DIR}/index.ts" <<'STUB'
/**
 * @axioledger/sdk — Auto-generated TypeScript SDK
 * Generated by: toolchain/build-scripts/generate-proto.sh
 *
 * STUB MODE: Chạy lại sau khi có .proto files từ fork-cosmos-cores.sh
 * Full codegen: pnpx telescope transpile --config toolchain/build-scripts/telescope.config.ts
 */

// ── Base Types ──────────────────────────────────────────────────────────────
export interface Coin         { denom: string; amount: string }
export interface DecCoin      { denom: string; amount: string }
export interface PageRequest  { key?: Uint8Array; offset?: bigint; limit?: bigint; count_total?: boolean; reverse?: boolean }
export interface PageResponse { next_key?: Uint8Array; total?: bigint }

// ── Auth Module ──────────────────────────────────────────────────────────────
export interface BaseAccount  { address: string; pub_key?: Any | null; account_number: bigint; sequence: bigint }
export interface Any          { type_url: string; value: Uint8Array }
export interface QueryAccountRequest  { address: string }
export interface QueryAccountResponse { account?: Any | null }

// ── Bank Module ──────────────────────────────────────────────────────────────
export interface MsgSend             { from_address: string; to_address: string; amount: Coin[] }
export interface MsgSendResponse     {}
export interface QueryBalanceRequest  { address: string; denom: string }
export interface QueryBalanceResponse { balance?: Coin | null }
export interface QueryAllBalancesRequest  { address: string; pagination?: PageRequest }
export interface QueryAllBalancesResponse { balances: Coin[]; pagination?: PageResponse | null }

// ── Staking Module ───────────────────────────────────────────────────────────
export type BondStatus = "BOND_STATUS_UNSPECIFIED" | "BOND_STATUS_UNBONDED" | "BOND_STATUS_UNBONDING" | "BOND_STATUS_BONDED"
export interface ValidatorDescription { moniker: string; identity: string; website: string; security_contact: string; details: string }
export interface CommissionRates      { rate: string; max_rate: string; max_change_rate: string }
export interface Commission           { commission_rates: CommissionRates; update_time?: Date }
export interface Validator {
    operator_address: string
    consensus_pubkey?: Any | null
    jailed: boolean
    status: BondStatus
    tokens: string
    delegator_shares: string
    description: ValidatorDescription
    commission: Commission
    min_self_delegation: string
}
export interface MsgDelegate         { delegator_address: string; validator_address: string; amount: Coin }
export interface MsgDelegateResponse {}
export interface MsgUndelegate       { delegator_address: string; validator_address: string; amount: Coin }

// ── Governance Module ────────────────────────────────────────────────────────
export type ProposalStatus =
    | "PROPOSAL_STATUS_UNSPECIFIED" | "PROPOSAL_STATUS_DEPOSIT_PERIOD"
    | "PROPOSAL_STATUS_VOTING_PERIOD" | "PROPOSAL_STATUS_PASSED"
    | "PROPOSAL_STATUS_REJECTED"     | "PROPOSAL_STATUS_FAILED"
export type VoteOption = "VOTE_OPTION_UNSPECIFIED" | "VOTE_OPTION_YES" | "VOTE_OPTION_ABSTAIN" | "VOTE_OPTION_NO" | "VOTE_OPTION_NO_WITH_VETO"
export interface TallyResult  { yes_count: string; abstain_count: string; no_count: string; no_with_veto_count: string }
export interface Proposal {
    id: bigint
    messages: Any[]
    status: ProposalStatus
    final_tally_result?: TallyResult | null
    submit_time?: Date
    deposit_end_time?: Date
    total_deposit: Coin[]
    voting_start_time?: Date
    voting_end_time?: Date
    metadata: string
    title: string
    summary: string
    proposer: string
}
export interface MsgSubmitProposal   { messages: Any[]; initial_deposit: Coin[]; proposer: string; metadata: string; title: string; summary: string }
export interface MsgVote             { proposal_id: bigint; voter: string; option: VoteOption; metadata: string }

// ── Distribution Module ──────────────────────────────────────────────────────
export interface MsgWithdrawDelegatorReward         { delegator_address: string; validator_address: string }
export interface MsgWithdrawDelegatorRewardResponse { amount: Coin[] }
export interface MsgWithdrawValidatorCommission         { validator_address: string }
export interface MsgWithdrawValidatorCommissionResponse { amount: Coin[] }

// ── IBC Core ─────────────────────────────────────────────────────────────────
export interface Height   { revision_number: bigint; revision_height: bigint }
export interface Packet   { sequence: bigint; source_port: string; source_channel: string; destination_port: string; destination_channel: string; data: Uint8Array; timeout_height: Height; timeout_timestamp: bigint }
export interface MsgTransfer { source_port: string; source_channel: string; token: Coin; sender: string; receiver: string; timeout_height: Height; timeout_timestamp: bigint; memo: string }
export interface MsgTransferResponse { sequence: bigint }

// ── Axioledger 5-Token Suite ─────────────────────────────────────────────────
/** $AXQ — Governance + Value Storage token (10 Trillion supply) */
export interface AXQToken     { denom: "uaxq"; amount: string }
/** $VPX — Validator Precision token */
export interface VPXToken     { denom: "uvpx"; amount: string }
/** $SQX — Sequential Chain token */
export interface SQXToken     { denom: "usqx"; amount: string }
/** $KPX — Kineto Protocol token */
export interface KPXToken     { denom: "ukpx"; amount: string }
/** $VRQ — Vera Ciphers / ZK Prover token */
export interface VRQToken     { denom: "uvrq"; amount: string }

export type AxioToken = AXQToken | VPXToken | SQXToken | KPXToken | VRQToken
STUB

    # Tạo client stub
    cat > "${OUT_DIR}/client.ts" <<'CLIENTSTUB'
/**
 * @axioledger/sdk/client — Axioledger Stargate Client
 * STUB: Thay thế bằng generated code sau khi có .proto files
 */

export interface AxioledgerClientConfig {
    rpcEndpoint: string
    prefix?: string   // default: "axio"
}

export interface SigningConfig extends AxioledgerClientConfig {
    mnemonic?: string
    privateKey?: Uint8Array
}

/** Stub class — replaced by Telescope-generated StargateClient */
export class AxioledgerQueryClient {
    constructor(public readonly config: AxioledgerClientConfig) {}
    async getBalance(address: string, denom: string): Promise<{ denom: string; amount: string }> {
        throw new Error("Stub — connect to live RPC endpoint")
    }
    async getAccount(address: string): Promise<{ address: string; sequence: bigint; account_number: bigint }> {
        throw new Error("Stub — connect to live RPC endpoint")
    }
}
CLIENTSTUB

    # Tạo index.ts re-export
    cat > "${OUT_DIR}/../index.ts" <<'SDKINDEX'
/**
 * @axioledger/sdk — Main entry point
 * Re-exports all generated types and client utilities.
 */
export * from "./generated/index.js"
export * from "./generated/client.js"
SDKINDEX

    log_ok "Stub types được tạo tại ${OUT_DIR}/"
    GENERATED_COUNT=$(find "${OUT_DIR}" -name "*.ts" 2>/dev/null | wc -l || echo "0")
    log_ok "Đã sinh ${GENERATED_COUNT} file TypeScript"
fi

# ─── Kiểm tra Go workspace ────────────────────────────────────────────────────
log_section "Kiểm tra Go workspace"
if command -v go &>/dev/null; then
    log_info "$(go version)"
    if [[ -f "${MONOREPO_ROOT}/go.work" ]]; then
        if go work sync 2>&1 | head -5; then
            log_ok "go work sync hoàn tất"
        else
            log_warn "go work sync: một số module chưa đồng bộ — chạy fork-cosmos-cores.sh"
        fi
    else
        log_warn "go.work chưa tồn tại — chạy fork-cosmos-cores.sh"
    fi
else
    log_warn "Go chưa cài — bỏ qua go work sync (chạy setup-environment.sh)"
fi

# ─── Kiểm tra Rust contracts ─────────────────────────────────────────────────
log_section "Kiểm tra Rust contracts"
if command -v cargo &>/dev/null; then
    log_info "$(rustc --version)"
    RUST_CONTRACTS=(
        "packages/axioledger/contracts/escrow/Cargo.toml"
    )
    for manifest in "${RUST_CONTRACTS[@]}"; do
        if [[ -f "${MONOREPO_ROOT}/${manifest}" ]]; then
            log_info "cargo check: ${manifest}"
            if cargo check --manifest-path "${MONOREPO_ROOT}/${manifest}" 2>&1 | tail -3; then
                log_ok "${manifest}: OK"
            else
                log_warn "${manifest}: check thất bại"
            fi
        fi
    done
else
    log_warn "Rust/Cargo chưa cài — bỏ qua contract check (chạy setup-environment.sh)"
fi

# ─── Tổng kết ─────────────────────────────────────────────────────────────────
FINAL_COUNT=$(find "${OUT_DIR}" -name "*.ts" 2>/dev/null | wc -l || echo "0")
echo ""
echo -e "${BOLD}==================================================================="
echo -e "  SINH MÃ HOÀN THÀNH — ${FINAL_COUNT} TypeScript files"
echo -e "===================================================================${NC}"
echo ""
echo "  Output: packages/axioledger/sdk/src/generated/"
echo ""
echo "  Bước tiếp theo:"
echo "    pnpm --recursive --filter \"./packages/**\" run typecheck"
echo "    pnpm --recursive --filter \"./packages/**\" run test"
echo ""
